<div class="alert alert-block alert-info">
<img src="./Imagenes/ITESO_Logo.png" style="width:500px;height:142px;" title="Logo ITESO">
<br><font face = "Times New Roman" size = "6"><b><center>Maestría en Sistemas Computacionales</center></b></font>
<br><font face = "Times New Roman" size = "5"><b><center>Programación para Análisis de Datos</center></b></font>

<b><br><font face = "Times New Roman" size = "4"><center>Unidad 2: Conceptos Generales</center></font>
<font face = "Times New Roman" size = "4"><center>Tema 2.3: Conceptos de Álgebra Lineal</center></font>
<font face = "Times New Roman" size = "4"><center>Subtema a: Vectores y Matrices</center></font></b>
</div>

## VECTORES Y MATRICES

Para el uso de operaciones vectoriales y matriciales en **Python** se empleará la librería **NumPy**.

#### La Librería NumPy
<br>
<img src="./Imagenes/NumPy_logo.png" style="width:341px;height:120px;" class="center">
<br>

**NumPy** es una librería de **Python** que le agrega mayor soporte para operaciones con vectores y matrices, constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con ellos. 

La documentación de **NumPy** se puede encontrar a través [de esta liga](https://numpy.org).

Para importar la librería se empleará la función `import numpy as np`, a partir de ello se podrá hacer uso de los distintos métodos de `numpy` invocándolo como `np`. 

Como primer ejemplo se generarán dos ***vectores*** que contengan 3 elementos cada uno empleando el método `.array()` el cual recibe los valores del vector en su argumento empleando corchetes `[]` y separados por comas `,`. A partir de esos vectores se realizarán varias operaciones:

In [1]:
#Importación de Librerías
import numpy as np                      

#Definición de Vectores 
A = np.array([1, 2, 3])                   
B = np.array([4, 5, 6])                    

#Operaciones con Vectores
C = A + B                                   
D = 5 * A                                   

#Impresión de los resultados
print("El vector A es:", A)
print("El vector B es:", B)
print("La suma de A+B es:", C)
print("La multiplicación de A por el escalar 5 es:", D)

El vector A es: [1 2 3]
El vector B es: [4 5 6]
La suma de A+B es: [5 7 9]
La multiplicación de A por el escalar 5 es: [ 5 10 15]


Ahora se generarán tres ***matrices*** de distintos tamaños:

* ***Matriz*** A de 2x3.
* ***Matriz*** B de 3x2.
* ***Matriz*** C de 2x2.

De manera similar a los ***vectores***, la creación de ***matrices*** se realiza con el método `.array()` el cual recibe los valores de la matriz en su argumento empleando corchetes `[]` para cada renglón, y separados por comas `,`. 

Se realizará la operación de multiplicación de ***matrices*** a través del método `.matmul()` de **NumPy**, el cual recibe en su argumento los elementos que se multiplicarán:

In [2]:
#Definición de Matrices
A = np.array([[1, 2, 3],[4, 5, 6]])        
B = np.array([[1, 2],[3, 4],[5,6]])        
C = np.array([[-1, -2],[0, -9]])           

#Operaciones con Matrices
D = np.matmul(A,B)                         
E = np.matmul(B,C)                         
#F = np.matmul(A,C)                         

#Impresión de los resultados
print("La matriz A es:\n", A)
print("\nLa matriz B es:\n", B)
print("\nLa matriz C es:\n", C)
print("\nLa multiplicación AxB es:\n", D)
print("\nLa multiplicación BxC es:\n", E)

La matriz A es:
 [[1 2 3]
 [4 5 6]]

La matriz B es:
 [[1 2]
 [3 4]
 [5 6]]

La matriz C es:
 [[-1 -2]
 [ 0 -9]]

La multiplicación AxB es:
 [[22 28]
 [49 64]]

La multiplicación BxC es:
 [[ -1 -20]
 [ -3 -42]
 [ -5 -64]]


<div class="alert alert-block alert-success">
<b>.: Fin del Subtema :.</b>
</div>

***Liga de aceso al siguiente Subtema:*** 
<br>[b. Estadística](b.%20Estadistica.ipynb)